# Online Retail Messy Dataset
This dataset is collected from kaggle. It is easy level of data cleaning where I'll apply my pandas skills to clean the data. It is real world messy dataset. Lets get started.

### Let's import pandas and numpy

In [1]:
import numpy as numpy
import pandas as pd

Now lets load the dataset using pandas

In [4]:
df=pd.read_csv("online_retail_real_world.csv")
df

,OrderID,CustomerID,ProductName,Brand,Raw_Weight,Country,OrderDate,UnitPrice
0,REC-861088,6120,Perly,Perly,100 g,"Morocco,United States",2024-02-22,13.18
1,REC-900952,12550,Prince Goût Chocolat,LU,300 g,"Algeria,Belgium,France,French Polynesia,German...",2024-11-13,1.50
2,REC-595965,6705,Excellence Noir Prodigieux 90% Cacao,"Lindt EXCELLENCE,Lindt",100g,"Argelia,Austria,Bélgica,Bulgaria,Canadá,Repúbl...",2025-02-02,12.99
3,REC-942653,8645,Tonik,عربي,22 g,Maroc,2024-12-11,14.82
4,REC-885998,14430,Sésame,Gerblé,230g,"Belgium, Bulgaria, France, en:switzerland",2025-08-21,18.40
...,...,...,...,...,...,...,...,...
2995,REC-867989,13739,Cocoa Orange,Nakd,NaN,en:GB,2025-03-30,3.78
2996,REC-774268,8212,Chocolate For Change Dark Chocolate With Orange,Coop,100 g,"Germany,en:united-kingdom",2025-03-23,14.41
2997,REC-432494,13398,Lait dessert,Fin Carré,200 g,"France, en:united-kingdom",2025-01-03,17.58
2998,REC-117507,8050,Rusticotti,Balocco,700,"Francia,Italia",2025-09-02,21.35
2999,REC-692469,11809,Cheddar & Onion Chutney Rolls,Higgidy,160g,en:gb,2024-12-07,7.47

Lets see the data now. What each column has , rows, stats summary and everything about the data.

In [5]:
df.sample(10)

,OrderID,CustomerID,ProductName,Brand,Raw_Weight,Country,OrderDate,UnitPrice
2673,REC-658763,10868,Barres Amandes et Noix de coco,"Crownfield, Lidl",4 x 40 g,France,2025-07-25,10.58
31,REC-212346,13782,Crunchy oats&honey,Nature Valley,42 g,"Bélgica,Francia,Alemania,Irlanda,Países Bajos,...",2024-05-25,4.18
2991,REC-568921,13985,Galletas Saladitas,Hacendado,350 g,España,2025-10-08,21.32
155,REC-245946,5600,Milka Tablette Noisette,"Milka, Mondelez",100g,"Algeria, Austria, Czech Republic, France, Germ...",2025-07-28,18.95
2710,REC-257882,6390,NaN,Huober,175g,"Frankreich,Deutschland,en:germany",2024-08-17,NaN
1560,REC-120006,7235,Tartines Craquantes Sarrasin,Le pain des fleurs,300 g,France,2026-01-10,12.02
2455,REC-115315,11500,BEEF JERKY ORIGINAL,JACK LINK'S,25 g,"Belgium,France,Switzerland,United Kingdom",2025-07-14,16.42
1251,REC-365666,10155,Chinois crème pâtissière,La Fournée Dorée,600 g,France,2025-12-06,8.14
1252,REC-613926,6869,"Grand cœur fondant, chocolat noisettes","Michel et Augustin,Ferrero",180 g,"France,Switzerland",2024-04-17,24.67
1962,REC-542499,14723,Noisette,"Carrefour, Carrefour Classic",125 g,"Belgique,France,Italie,Espagne",2025-07-29,NaN

In [9]:
display(df.dtypes) #checking data types of cols
display(df.info()) #general info about data.
df.describe() #stats summary of numeric value

OrderID            str
CustomerID       int64
ProductName        str
Brand              str
Raw_Weight         str
Country            str
OrderDate          str
UnitPrice      float64
dtype: object

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      3000 non-null   str
 1   CustomerID   3000 non-null   int64
 2   ProductName  2904 non-null   str
 3   Brand        2665 non-null   str
 4   Raw_Weight   2488 non-null   str
 5   Country      3000 non-null   str
 6   OrderDate    3000 non-null   str
 7   UnitPrice    2615 non-null   float64
dtypes: float64(1), int64(1), str(6)
memory usage: 187.6 KB

None

         CustomerID    UnitPrice
count   3000.000000  2615.000000
mean    9989.842333    12.992417
std     2871.959873     6.963856
min     5011.000000     1.000000
25%     7454.750000     6.985000
50%    10066.000000    13.160000
75%    12527.250000    18.960000
max    14998.000000    24.990000

In [12]:
#making a copy of the file first so the original is not modified.
dfc=df.copy()
dfc.head()

,OrderID,CustomerID,ProductName,Brand,Raw_Weight,Country,OrderDate,UnitPrice
0,REC-861088,6120,Perly,Perly,100 g,"Morocco,United States",2024-02-22,13.18
1,REC-900952,12550,Prince Goût Chocolat,LU,300 g,"Algeria,Belgium,France,French Polynesia,German...",2024-11-13,1.50
2,REC-595965,6705,Excellence Noir Prodigieux 90% Cacao,"Lindt EXCELLENCE,Lindt",100g,"Argelia,Austria,Bélgica,Bulgaria,Canadá,Repúbl...",2025-02-02,12.99
3,REC-942653,8645,Tonik,عربي,22 g,Maroc,2024-12-11,14.82
4,REC-885998,14430,Sésame,Gerblé,230g,"Belgium, Bulgaria, France, en:switzerland",2025-08-21,18.40

In [ ]:
#Renaming columns to match the snakecase pattern
dfc=dfc.rename(columns={"OrderID":"order_id",
                       "CustomerID":"customer_id",
                       "ProductName":"product_name",
                       "Brand":"brand",
                       "Raw_Weight":"raw_weight",
                       "Country":"country",
                       "OrderDate":"order_date",
                       "UnitPrice":"unit_price"})
dfc.columns.tolist()

# We could have used df=df.columns("col1",col2,..) as well with changed col names or used regex.

['order_id',
 'customer_id',
 'product_name',
 'brand',
 'raw_weight',
 'country',
 'order_date',
 'unit_price']

In [20]:
dfc.sample(10)

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
590,REC-695435,13986,Cracotte fibres,LU,250 g,France,2025-07-20,16.86
1141,REC-744133,13201,Fiori d'acqua,NaN,250 g,"en:italy, en:france",2024-06-12,17.95
1798,REC-101499,5263,Grany Chocolat 5 céréales,NaN,"208 g (10x20,8 g)",France,2025-06-01,16.07
52,REC-754969,6085,Pringles Sare,Pringles,165 g,"Armenia,Bielorrusia,Bélgica,Bosnia y Herzegovi...",2024-07-27,2.70
53,REC-528239,12090,wasa,"Barilla,Wasa",270 g,"France,Guadeloupe,Italy,Switzerland",2025-04-10,18.39
702,REC-320838,5258,Biscuit saveur vanille citron,"Gerlinéa, Ma Pause Gerlinéa",156g,"France, en:switzerland",2025-11-02,4.63
2322,REC-996928,7996,Chocolate Negro 55%,Hacendado,150g,"Marruecos,España",2025-09-11,7.32
1533,REC-467524,12183,Tuiles goût salé,Bouton d'or,170 g,France,2025-06-13,20.94
2804,REC-844095,5948,Biscuit sésame Gerblé,gerblé,NaN,France,2024-02-09,16.94
552,REC-790841,11019,LOTUS BISCOFF Speculoos Fourré - Crème Speculo...,Lotus,150 g,"Australia,Bélgica,República Checa,Francia,Alem...",2025-03-21,11.31

In [24]:
#Finding Null values sum of each col
print(dfc.isna().sum())
(dfc.isna().sum()/len(df))*100 #percentage of na

order_id          0
customer_id       0
product_name     96
brand           335
raw_weight      512
country           0
order_date        0
unit_price      385
dtype: int64

order_id         0.000000
customer_id      0.000000
product_name     3.200000
brand           11.166667
raw_weight      17.066667
country          0.000000
order_date       0.000000
unit_price      12.833333
dtype: float64

In [ ]:
#Deleting the empty rows which has product name. 
dfc.dropna(subset=['product_name'],inplace=True)
dfc.isna().sum()

order_id          0
customer_id       0
product_name      0
brand           321
raw_weight      484
country           0
order_date        0
unit_price      289
dtype: int64

In [ ]:
#Filling na values with mean of unit_price, cause dats is normally distributed.
#dfc["unit_price"]=dfc["unit_price"].fillna(dfc["unit_price"].mean())
dfc.isna().sum()
dfc["unit_price"].skew() #Negatively skewed only a bit.

np.float64(-0.04256322147763501)

In [37]:
# Lets see one more random rows to find out what to fix in our data.
dfc.sample(20)

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
2167,REC-224121,12228,sablé canelle,NaN,NaN,en:ma,2024-08-08,1.830000
1635,REC-928943,8231,Rich Tea Biscuits,Tower Gate,300 g,United Kingdom,2025-12-12,12.992417
2468,REC-968085,14371,Classic Collection Chocolate Bars,Green & Blacks,NaN,"France, United States, en:united-kingdom",2024-03-06,16.750000
1494,REC-856276,13683,Ficelles Olives Vertes et Noires,Kambly,100 g,France,2025-03-03,5.550000
1144,REC-631872,11310,Leader chips,NaN,20/01/2024,en:MA,2025-02-06,12.992417
2315,REC-327209,6442,Noir 70% noisettes et amandes caramélisées,côte d'or,100g,France,2025-02-15,23.510000
334,REC-985358,10037,Chocolat Bio noir 85%,Côte d'Or,90 g,"Belgique,France,La Réunion",2025-06-10,12.992417
1044,REC-974451,10818,all butter scottish shortbread fingers,Lidl,NaN,France,2025-02-13,12.130000
1516,REC-769574,5411,50G RICOLA MENTHOL,Ricola,50 g,France,2026-01-22,15.240000
1029,REC-257543,9713,Cioccolato al latte,"LU,Mikado,Mondelez",75g,"Bélgica,Francia,Italia,España,Reino Unido,Esta...",2026-02-04,18.900000
2767,REC-730439,11624,Prinzenrolle,DeBeukelar,450g,en:de,2026-01-29,23.140000
1181,REC-930429,12217,Peanut,m&m's,250g,"France,Germany,Italy,Luxembourg,Romania,Switze...",2025-01-12,5.880000
1006,REC-874806,10855,Biscuits craquants saveur citron,"Karelea, Léa nature",132 g,France,2025-06-25,5.900000
302,REC-419555,14119,Roudor,St Michel,150 g,France,2024-03-31,1.020000
1084,REC-772291,11300,Kurkure,Kurkure,78 g,"France,India,Nepal,Spain,Canada",2025-07-14,12.180000
245,REC-594620,8463,Cheese & Onion Flavour Potato Crisps,Walkers,25 g,United Kingdom,2025-05-19,7.050000
588,REC-196794,5746,Leibniz Butterkeks,"Bahlsen,Leibniz",120g,"Germany,Italy,Morocco",2025-09-08,12.992417
278,REC-452636,5813,Bimo,Merendina,36 g,Morocco,2025-03-02,12.780000
330,REC-348747,6106,Excellence À la Pointe de Fleur de Sel Noir,Lindt,100 g,"Bélgica,Dinamarca,Francia,Alemania,Italia,País...",2025-04-20,12.480000
655,REC-850125,7216,Muesli Bars Chocolate,Crownfield,8x25 gram,"Bulgarie,France,Allemagne,Irlande,Royaume-Uni",2024-07-07,10.240000

So the average_price has defects in its value. It's messy, differerent units, and extra spaces and many things. 
I"m gonna use regex to replace all which are not numbers and decimals with "".

In [ ]:
#Cleaning the avg_price column mess with regex
dfc['raw_weight'] = dfc['raw_weight'].str.extract(r'(\d+\.?\d*)').astype(float)

AttributeError: Can only use .str accessor with string values, not floating

In [45]:
dfc.sample(20)

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
1622,REC-971893,8711,Tartines grillées craquantes au froment 250g,U,250.00,France,2024-09-15,22.740000
2504,REC-991264,10838,Dark 85% cacao,Nestlé,120.00,"Spain, en:morocco",2025-11-27,3.120000
2711,REC-457077,11150,Pom-Bär Original,"Intersnack Deutschland SE, Pombär",75.00,"en:germany, en:Germany",2026-02-02,21.020000
2074,REC-869438,8820,Biscuits à l'avoine complète et aux pépites ch...,"U, U Bio",130.00,France,2024-09-14,21.030000
345,REC-597548,12785,Mini BN Chocolat,BN,175.00,"Belgique,France,Maroc,La Réunion,Suisse",2025-04-24,12.690000
1012,REC-482706,7384,Dinosaurus,"Artiach,Mondelez",411.00,"en:spain, en:france",2025-02-08,6.810000
2693,REC-737641,11717,Goûter fourré cacao rond BIO,"Chabrior, Chabrior Bio",185.00,"France,Belgium",2025-02-28,12.992417
1846,REC-485097,12291,Salt And Vinegar Flavour Peanuts,KP,225.00,en:United Kingdom,2025-05-08,23.780000
2587,REC-465416,14021,Lays 20rs,"PepsiCo,Lay's",55.00,Inde,2025-10-14,6.980000
574,REC-189159,13071,RASPBERRY WHOLEGRAIN OAT BARS,stoats,4.00,en:gb,2024-04-22,8.560000
1641,REC-862062,8260,Lutti best fizz tubo 550g,Lutti,0.55,France,2024-05-24,14.130000
2665,REC-757695,9163,Petit Beurre Tablette Chocolat au lait,Sondey,150.00,"France,Switzerland",2025-10-25,14.740000
1529,REC-781241,14005,Biscuits Complets Avoine et blé Bio,"Aachener Zucker- und Backwaren Paul Schaeffer,...",200.00,"Frankreich,Deutschland",2025-01-12,11.490000
2004,REC-456735,14655,Sweet Chilli Rice Crackers,Aldi,NaN,United Kingdom,2024-09-14,1.430000
2821,REC-568240,10460,Barres GOURMANDES,Carrefour,140.00,"Belgium,France, Italie, Espagne",2025-10-10,7.930000
2623,REC-229696,11481,Mini Breadsticks,Tesco,NaN,en:United Kingdom,2024-07-21,22.330000
2424,REC-132519,9486,Eat Natural Dark Chocolate With Cranberries An...,Eat Natural,40.00,United Kingdom,2026-01-03,13.950000
2768,REC-774116,5812,Dairy Milk Marvellous Creations Jelly Popping ...,"Cadbury, Mondelez",160.00,en:gb,2025-12-09,4.740000
1494,REC-856276,13683,Ficelles Olives Vertes et Noires,Kambly,100.00,France,2025-03-03,5.550000
1617,REC-185822,7896,"Grainéa Abricot barres aux 5 céréales Maîs,Blé...",GRAINÉA,126.00,Frankrijk,2024-09-21,24.190000

In [ ]:
dfc.isnull().sum()
dfc.describe()

        customer_id   raw_weight   unit_price
count   2904.000000  2418.000000  2904.000000
mean    9988.193871   179.249915    12.992417
std     2867.581771   143.467400     6.608137
min     5011.000000     0.185000     1.000000
25%     7457.250000    95.000000     7.630000
50%    10079.000000   150.000000    12.992417
75%    12511.250000   247.250000    18.332500
max    14997.000000  1000.000000    24.990000

In [ ]:
#checking the values of raw_weight
display(dfc[dfc["raw_weight"]] <=1)

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
382,REC-550308,7241,Petites Madeleines,St Michel,1.000,"France, en:reunion",2025-01-22,12.992417
661,REC-271727,10870,Muesli CroustillantNoix,Auchan,0.450,"France,Spain, Monde",2024-08-18,9.390000
912,REC-846891,11252,Fluffy Milky,best biscuits,1.000,en:Morocco,2025-06-06,15.860000
975,REC-378786,7970,Panettone Classico,Favorina,1.000,Spagna,2025-01-30,8.600000
1243,REC-378837,6892,Lutti guimauve chocolat,Lutti,0.185,France,2025-06-19,23.560000
1284,REC-432468,14210,raw fruit & nut bar,nakd.,1.000,"Spain, en:united-kingdom",2025-05-01,22.520000
1413,REC-513581,11470,Home chip,Mccain,1.000,United Kingdom,2024-03-03,12.992417
1428,REC-254549,8129,Chocolate Sea Salt,RXBAR,1.000,United States,2025-03-23,18.000000
1631,REC-577588,8792,Original Saltine Crackers,Premium,1.000,United States,2025-09-09,1.920000
1641,REC-862062,8260,Lutti best fizz tubo 550g,Lutti,0.550,France,2024-05-24,14.130000
1660,REC-911324,14318,Mix milk,Balconi,1.000,"Belgium, France, Germany, en:morocco",2024-08-04,4.280000
1671,REC-117583,8120,Fruit Snack,Welch's,0.800,"Andorra,United States",2025-12-19,12.992417
1692,REC-560283,14299,Nacho Cheese Flavored Tortilla Chips,Doritos,1.000,"Bolivia,Estados Unidos",2024-08-22,12.992417
2000,REC-177589,9352,Finest Sea Salt And Black Pepper Crisps,NaN,1.000,en:United Kingdom,2025-12-29,19.010000
2002,REC-111010,7828,Flocons d'Avoine,NaN,0.500,"France,Monde",2025-02-15,17.810000
2187,REC-619067,13299,Arlequin Original,Lutti,0.250,France,2024-09-19,21.740000
2301,REC-507312,7577,Baked Squeezed Pretzels,Elephant,1.000,"Germany, Morocco, en:france",2025-11-01,12.992417
2347,REC-879118,11703,Surfizz Goûts Fruits,Lutti,0.200,France,2024-07-19,4.820000
2392,REC-188902,5940,Organic Sea Salt Multigrain Tortilla Chips,NaN,1.000,"en:United States,en:United States, World",2024-08-22,19.480000
2494,REC-666258,5509,"Galactic Brownies With Chocolate Candies, Choc...",Mr. Brownie,1.000,"Frankreich, Spanien, Welt, Germany",2026-01-27,22.360000
2614,REC-880363,11730,XXL Erdnüsse,Alesto,1000.000,"Франция,Германия,Швеция,Обединено кралство Вел...",2025-08-18,14.280000
2902,REC-420495,10110,Raspberry Porridge Oat Bar,Stoats,1.000,United Kingdom,2024-12-31,16.140000
2915,REC-770896,7552,Extra fresh professional,"Wrigley‘s,extraFresh",1.000,Germany,2025-07-19,6.230000

In [55]:
#Deleting the rows which has less than 1 value cause it doesnt make any sense.
# Keep only rows where raw_weight is 1 or more
dfc = dfc[dfc['raw_weight'] >= 1]
# we could have used dfc.drop(dfc[dfc'raw_weight'<=1],inplace=True).. this works as well.

In [56]:
print(dfc.info())
dfc.describe()

<class 'pandas.DataFrame'>
Index: 2411 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      2411 non-null   str
 1   customer_id   2411 non-null   int64
 2   product_name  2411 non-null   str
 3   brand         2166 non-null   str
 4   raw_weight    2411 non-null   float64
 5   country       2411 non-null   str
 6   order_date    2411 non-null   str
 7   unit_price    2411 non-null   float64
dtypes: float64(2), int64(1), str(5)
memory usage: 169.5 KB
None

        customer_id   raw_weight   unit_price
count   2411.000000  2411.000000  2411.000000
mean    9984.200747   179.769125    13.040554
std     2886.557170   143.351038     6.621648
min     5011.000000     1.000000     1.000000
25%     7412.000000   100.000000     7.660000
50%    10103.000000   150.000000    12.992417
75%    12554.500000   250.000000    18.405000
max    14997.000000  1000.000000    24.990000

In [58]:
dfc.sample(20)

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
1178,REC-503494,14481,Tartines craquantes bio à la châtaigne sans gl...,"Ekibio,Le Pain des fleurs",150.0,"Belgium,France,Switzerland",2026-01-09,9.600000
2513,REC-905940,13142,Ricola douceur de miel,NaN,50.0,"Brazil en:france, en:france",2025-07-14,24.460000
2436,REC-523674,13062,madeleines coquilles,Tante Odile,400.0,France,2024-10-13,23.200000
1265,REC-710440,10010,Protein Bar Chocolate Brownie,Lidl,135.0,"France,Italy,Spain,United Kingdom",2025-07-15,17.300000
1812,REC-694391,10758,Chips les natures craquantes,Bret's,250.0,France,2025-12-23,2.250000
36,REC-499346,14145,Pains au lait x10,Pasquier,350.0,"Belgique,France,Suisse,Royaume-Uni,États-Unis",2024-04-08,22.820000
17,REC-506660,10724,Excellence Noir Puissant 85% Cacao,Lindt,100.0,"Autriche,Belgique,France,Allemagne,Italie,Maro...",2024-12-09,14.000000
2647,REC-435783,10459,Wafer,Sondey,280.0,"Bulgaria, en:romania",2025-06-18,22.390000
2392,REC-188902,5940,Organic Sea Salt Multigrain Tortilla Chips,NaN,1.0,"en:United States,en:United States, World",2024-08-22,19.480000
902,REC-760379,10111,Menier Pâtissier Tablette,"Nestlé, Menier",200.0,France,2025-04-03,16.250000
1047,REC-918691,12901,Lentil bites sea salt,Lidl,110.0,"Ireland,United Kingdom",2025-02-18,16.600000
1609,REC-346480,5746,Crunchy Avena y Miel,"Nature Valley,General Mills",210.0,"Portugal,España",2026-01-23,20.470000
303,REC-885496,9271,Tartined Craquantes Châtaigne,"Jardin bio, Léa Nature",150.0,France,2025-02-10,5.700000
1210,REC-344208,9651,Rosemary Crackers,Deluxe,170.0,United Kingdom,2024-02-05,12.992417
1865,REC-824368,13005,High protein milk chocolate crisp,Fincarre,90.0,"Netherlands, Romania, en:united-kingdom",2024-12-16,18.560000
136,REC-145901,9071,Belvita Brut & 5 céréales complètes,Lu,400.0,"Belgique,France,Luxembourg,Nouvelle-Calédonie,...",2024-07-18,24.590000
378,REC-450859,14600,Chocolat noir Bio 70%,"Côte d'Or,Mondelez International",90.0,"Belgium,France,Réunion",2025-05-14,10.200000
1661,REC-765162,12371,Chocolate puro,Valor,300.0,Spain,2025-07-12,12.992417
2423,REC-737554,6712,Salted Lentil Chips,NaN,18.0,en:United Kingdom,2024-12-31,17.820000
682,REC-982782,5760,Crunchy Variety,"General Mills, Nature Valley",42.0,"France,United Kingdom",2024-06-30,12.992417

I see that brand name and product name has brand name, manufacturer, company like that. I'll only keep the first one.

In [62]:
#I'm only keeping first part of brand.
#splits the product into a list and takes the first element and strips it.
dfc['product_name']=dfc["product_name"].str.split(",").str[0].str.strip()

dfc['brand']=dfc["brand"].str.split(",").str[0].str.strip()
dfc.sample(10)

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
2767,REC-730439,11624,Prinzenrolle,DeBeukelar,450.0,en:de,2026-01-29,23.140000
2978,REC-497381,11550,Prince Maxi Gourmand,LU,250.0,"Belgium,France,Netherlands",2025-01-04,12.992417
2082,REC-254398,6320,Brioche muffin bio x 5 250g blg,La Boulangère,250.0,France,2024-05-07,2.560000
1157,REC-416620,12032,Noir amandes entieres,Carrefour,200.0,"France,Italy,Spain",2024-09-12,17.000000
1792,REC-569488,7725,Crispy Biscuit Slices,McVitie's,174.0,en:gb,2024-09-23,10.100000
1965,REC-134302,13349,Chocolat noir dessert bio,Bio Village,200.0,France,2024-04-24,3.840000
1142,REC-276523,14324,Mini fish,Gullón,350.0,"France, Spain, en:morocco",2025-12-08,3.520000
2595,REC-554812,6814,Chocolate Salted Caramel Flavour Vitamin & Pro...,Fulfil,40.0,"Spanien, Vereinigtes Königreich, Germany",2025-08-15,22.700000
792,REC-559769,9717,Multigrain Crackers,Rivercote (LIDL),170.0,France,2025-03-28,11.180000
1814,REC-699551,10641,Stylesse Chocolat Noir,Carrefour,300.0,"France,Italie,Maroc,Pologne,Espagne",2024-06-12,4.330000

The product name has some numbers * as well lets only keep the text in there.

In [64]:
dfc["product_name"]=dfc["product_name"].replace(r'[^a-zA-Z\s]','',regex=True).str.strip()
dfc

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
0,REC-861088,6120,Perly,Perly,100.0,"Morocco,United States",2024-02-22,13.18
1,REC-900952,12550,Prince Got Chocolat,LU,300.0,"Algeria,Belgium,France,French Polynesia,German...",2024-11-13,1.50
2,REC-595965,6705,Excellence Noir Prodigieux Cacao,Lindt EXCELLENCE,100.0,"Argelia,Austria,Bélgica,Bulgaria,Canadá,Repúbl...",2025-02-02,12.99
3,REC-942653,8645,Tonik,عربي,22.0,Maroc,2024-12-11,14.82
4,REC-885998,14430,Ssame,Gerblé,230.0,"Belgium, Bulgaria, France, en:switzerland",2025-08-21,18.40
...,...,...,...,...,...,...,...,...
2993,REC-796830,11134,Sabls noisette chocolat,Bonne Maman,150.0,Francia,2024-12-14,21.72
2996,REC-774268,8212,Chocolate For Change Dark Chocolate With Orange,Coop,100.0,"Germany,en:united-kingdom",2025-03-23,14.41
2997,REC-432494,13398,Lait dessert,Fin Carré,200.0,"France, en:united-kingdom",2025-01-03,17.58
2998,REC-117507,8050,Rusticotti,Balocco,700.0,"Francia,Italia",2025-09-02,21.35
2999,REC-692469,11809,Cheddar Onion Chutney Rolls,Higgidy,160.0,en:gb,2024-12-07,7.47

In [67]:
dfc.sample(10)
dfc.isnull().sum()

order_id          0
customer_id       0
product_name      0
brand           245
raw_weight        0
country           0
order_date        0
unit_price        0
dtype: int64

In [88]:
dfc["brand"].nunique()
dfc.shape
(dfc.isnull().sum()/len(df))*100
(dfc[dfc["brand"].isnull()])

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
8,REC-202400,10397,Milk chocolate bar,NaN,150.0,"Algeria,Cameroon,France,Morocco,Spain",2024-08-04,11.08
11,REC-965916,6325,Sable coco Henry s g,NaN,42.0,Maroc,2024-07-02,2.64
38,REC-400480,14530,Brioche Tranche Bio g,NaN,400.0,France,2024-11-13,3.20
44,REC-900195,13320,La gche tranche,NaN,500.0,"France,Germany,Switzerland",2025-08-04,11.15
56,REC-440963,6157,Biscuit raisins,NaN,270.0,"France,Suisse",2024-06-09,16.66
...,...,...,...,...,...,...,...,...
2973,REC-906092,13589,Oreo Golden,NaN,500.0,"Dinamarca,Francia,Marruecos,Noruega,España,Suecia",2024-06-05,7.92
2982,REC-834515,11654,Ferrero Collection,NaN,269.0,"France,Allemagne",2025-03-16,8.68
2984,REC-236378,10559,Nero nero,NaN,75.0,"France,Italie",2024-05-09,23.42
2986,REC-658055,6839,Active Integral Gulln,NaN,840.0,"Francia,España",2025-12-14,4.61
2990,REC-958945,9639,Digestives Milk Chocolate,NaN,433.0,"France,United Kingdom",2024-02-11,2.42

In [91]:
#Lets  fill the null brand names with "Unknown"
dfc["brand"]=dfc["brand"].fillna("Unknown")

In [93]:
dfc.dtypes

order_id            str
customer_id       int64
product_name     object
brand            object
raw_weight      float64
country             str
order_date          str
unit_price      float64
dtype: object

Lets convert float cols to int

In [95]:
dfc[["raw_weight","unit_price"]]=dfc[["raw_weight","unit_price"]].astype(int)

In [96]:
dfc.dtypes

order_id           str
customer_id      int64
product_name    object
brand           object
raw_weight       int64
country            str
order_date         str
unit_price       int64
dtype: object

In [ ]:
#checking if there are duplicates order id
dfc.duplicated(subset="order_id").sum()

np.int64(5)

In [104]:
#checking if there are duplicated customer id
dfc.duplicated(subset="customer_id").sum()

np.int64(283)

In [105]:
#checking both order and customer id.
dfc.duplicated(subset=["order_id","customer_id"]).sum()

np.int64(0)

In [109]:
#lets check the order_id duplication.other dups are normal.
dfc[dfc.duplicated(subset="order_id",keep=False)].sort_values("order_id")

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
1311,REC-133930,12583,Tartelettes framboise,Bonne Maman,135,"Belgique,France,Allemagne,Suisse,Royaume-Uni",2024-04-27,19
1535,REC-133930,12702,Galleta de mantequilla con tableta de chocolat...,Carrefour BIO,150,"France,Italy,Poland,Romania,Spain,Switzerland,...",2025-10-06,6
574,REC-189159,13071,RASPBERRY WHOLEGRAIN OAT BARS,stoats,4,en:gb,2024-04-22,8
1942,REC-189159,13365,Mini tartelettes,Unknown,250,France,2025-12-15,13
1320,REC-388577,12823,Doritos Tangy Cheese,Doritos,180,United Kingdom,2025-03-01,19
2492,REC-388577,13112,Grain Free Tortilla Chips,Siete,5,"France, World, en:united-states",2024-04-23,15
1129,REC-660334,12862,Cration Crme Brle,Lindt,150,France,2025-11-24,20
1314,REC-660334,5314,Pains au chocolat x,Marque Repère,360,France,2024-03-05,21
1443,REC-771999,8170,Brossard brownie familial pepites de chocolat gr,Brossard,285,France,2025-08-05,12
2655,REC-771999,14873,Fruit Fibre Bars,Nākd,44,en:United Kingdom,2024-07-21,9

In [110]:
#Deleting dubs order id all because it doesn't match with other column, so its an error from the system generating order ids.
dfc.drop_duplicates(subset="order_id")

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
0,REC-861088,6120,Perly,Perly,100,"Morocco,United States",2024-02-22,13
1,REC-900952,12550,Prince Got Chocolat,LU,300,"Algeria,Belgium,France,French Polynesia,German...",2024-11-13,1
2,REC-595965,6705,Excellence Noir Prodigieux Cacao,Lindt EXCELLENCE,100,"Argelia,Austria,Bélgica,Bulgaria,Canadá,Repúbl...",2025-02-02,12
3,REC-942653,8645,Tonik,عربي,22,Maroc,2024-12-11,14
4,REC-885998,14430,Ssame,Gerblé,230,"Belgium, Bulgaria, France, en:switzerland",2025-08-21,18
...,...,...,...,...,...,...,...,...
2993,REC-796830,11134,Sabls noisette chocolat,Bonne Maman,150,Francia,2024-12-14,21
2996,REC-774268,8212,Chocolate For Change Dark Chocolate With Orange,Coop,100,"Germany,en:united-kingdom",2025-03-23,14
2997,REC-432494,13398,Lait dessert,Fin Carré,200,"France, en:united-kingdom",2025-01-03,17
2998,REC-117507,8050,Rusticotti,Balocco,700,"Francia,Italia",2025-09-02,21
2999,REC-692469,11809,Cheddar Onion Chutney Rolls,Higgidy,160,en:gb,2024-12-07,7

In [112]:
dfc.info()

<class 'pandas.DataFrame'>
Index: 2411 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      2411 non-null   str
 1   customer_id   2411 non-null   int64
 2   product_name  2411 non-null   object
 3   brand         2411 non-null   object
 4   raw_weight    2411 non-null   int64
 5   country       2411 non-null   str
 6   order_date    2411 non-null   str
 7   unit_price    2411 non-null   int64
dtypes: int64(3), object(2), str(3)
memory usage: 169.5+ KB

### Handling errors in country names.
### I'll use the first country name, remove en: at the beginning

In [113]:
dfc.sample(10)

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
1807,REC-423178,12254,Chocolat noir ptisser Tablette de g,U,200,France,2025-03-22,16
1191,REC-949086,9818,Kinder joy,Ferrero,60,France,2025-04-27,18
710,REC-461910,14376,Manchego Green Olive,Manomasa,140,en:gb,2026-02-04,1
734,REC-127463,13169,Knoppers Einzelpack,Storck,25,"Dänemark,Frankreich,Deutschland,Marokko,Polen,...",2025-01-31,24
450,REC-402691,13147,Schokobons,Kinder,200,"Autriche,Belgique,France,Allemagne,Espagne",2025-05-26,21
1357,REC-955736,11280,Ricola eucalyptus,Ricola,70,France,2026-02-01,3
1076,REC-915625,14356,G HAPPY BOX HARIBO,Haribo,600,"France,Suisse",2025-02-02,14
2003,REC-272885,12736,Tendre cur chocolat,Bonne maman,300,"Francia,Serbia",2025-09-26,9
2419,REC-733355,12789,Crushed Sea Salt Black Peppercorn Crisps,Walkers,150,en:United Kingdom,2024-04-27,10
2668,REC-846401,9233,Tastino Biscuiti Petit beurre,Tastino,450,"Hungary,Romania",2024-03-01,11

In [ ]:
dfc['country'] = dfc['country'].str.split(',').str[0] # taking the first country.
dfc["country"]=dfc["country"].str.replace("en:","",case=False)

In [116]:
dfc.sample(20)

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
2722,REC-259895,13423,Butterfly,Kambly,100,France,2025-01-04,21
611,REC-428280,13347,CRUNCHY SAVOURY WHOLEWHEAT STICKS,Unknown,200,France,2024-10-15,9
1936,REC-569021,8333,Petit ourson guimauve,CEMOI,170,France,2025-07-13,9
1295,REC-497572,7573,Kingsize Peanuts Unsalted,Snacks of the world,375,France,2025-07-03,12
1637,REC-874194,9592,Lait amandes caramlises,fin CARRÉ,200,Finlande,2025-11-15,12
1499,REC-919137,7180,Milk Chocolate Truffles,Unknown,200,Italy,2025-05-26,21
1155,REC-391046,13826,tartines craquantes riz chtaigne,Céréal Bio,145,France,2024-07-28,18
215,REC-222245,8897,Chocolate negro,Carrefour BIO,100,Belgium,2025-03-28,9
1505,REC-999167,10562,Potato Cakes,Warburtons,6,gb,2024-11-01,20
729,REC-254475,11515,Lulu LOurson Chocolat,LU,150,France,2025-09-08,1
1322,REC-870994,6103,Oreo Original,Oreo,154,France,2024-10-06,5
1268,REC-903339,12486,Barritas de galleta rellenas de arndanos,Hacendado,125,Portugal,2025-03-31,14
2884,REC-453635,10969,Crunchy Oats Honey Granola Bars,Harvest Morn,210,Ireland,2024-03-08,3
1073,REC-728214,5179,Chouchou,Alesto,250,Frankrijk,2025-12-26,21
1441,REC-156780,12886,Petit beurre g,U,200,France,2025-07-31,12
245,REC-594620,8463,Cheese Onion Flavour Potato Crisps,Walkers,25,United Kingdom,2025-05-19,7
2566,REC-652939,11997,Kinder Country,Unknown,23,Österreich,2025-05-24,17
1509,REC-692106,13978,Sea Salt Sourdough Flatbreads,Peter's Yard,115,gb,2025-03-12,1
2510,REC-111609,5943,Nachos,Snack Day,150,España,2024-11-04,12
1394,REC-106778,5126,Kinder Pingui,Kinder,30,Bosnie-Herzégovine,2024-08-25,20

In [122]:
#Lowercasing brand, country, product_name rows
dfc["product_name"]=dfc["product_name"].str.lower()
dfc["country"]=dfc["country"].str.lower()
dfc["brand"]=dfc["brand"].str.lower()

In [134]:
#reseting index.
dfc.reset_index(inplace=True,drop=True)
dfc.drop(columns="index")

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
0,REC-861088,6120,perly,perly,100,morocco,2024-02-22,13
1,REC-900952,12550,prince got chocolat,lu,300,algeria,2024-11-13,1
2,REC-595965,6705,excellence noir prodigieux cacao,lindt excellence,100,argelia,2025-02-02,12
3,REC-942653,8645,tonik,عربي,22,maroc,2024-12-11,14
4,REC-885998,14430,ssame,gerblé,230,belgium,2025-08-21,18
...,...,...,...,...,...,...,...,...
2406,REC-796830,11134,sabls noisette chocolat,bonne maman,150,francia,2024-12-14,21
2407,REC-774268,8212,chocolate for change dark chocolate with orange,coop,100,germany,2025-03-23,14
2408,REC-432494,13398,lait dessert,fin carré,200,france,2025-01-03,17
2409,REC-117507,8050,rusticotti,balocco,700,francia,2025-09-02,21
2410,REC-692469,11809,cheddar onion chutney rolls,higgidy,160,gb,2024-12-07,7

In [141]:
#inspecting the data after cleaning.

display(dfc.head(20))
display(dfc.info())
display(dfc.shape)
display(dfc.describe())
display(dfc.isnull().sum())

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
0,REC-861088,6120,perly,perly,100,morocco,2024-02-22,13
1,REC-900952,12550,prince got chocolat,lu,300,algeria,2024-11-13,1
2,REC-595965,6705,excellence noir prodigieux cacao,lindt excellence,100,argelia,2025-02-02,12
3,REC-942653,8645,tonik,عربي,22,maroc,2024-12-11,14
4,REC-885998,14430,ssame,gerblé,230,belgium,2025-08-21,18
5,REC-674324,6760,,j. d. gross,125,austria,2024-09-08,19
6,REC-867660,8420,cristaline eau de source l,cristaline,500,belgium,2024-10-10,3
7,REC-448132,9144,henrys,henry's,42,maroc,2024-12-30,17
8,REC-202400,10397,milk chocolate bar,unknown,150,algeria,2024-08-04,11
9,REC-386572,13888,organic dark chocolate bar,green & black's,90,france,2025-10-15,12
10,REC-965916,6325,sable coco henry s g,unknown,42,maroc,2024-07-02,2
11,REC-735024,8672,biscuits croquants au coeur onctueux de nutella,nutella,304,francia,2024-12-11,10
12,REC-866242,13720,tartine croustillante authentique,wasa,275,france,2024-12-16,6
13,REC-167785,6250,excellence noir intense cacao,lindt,100,algérie,2024-10-26,1
14,REC-625106,12696,lightly sea salted crisps,tyrrell's,150,france,2024-09-16,1
15,REC-399127,6000,dark chocolate,green and black,90,belgium,2025-09-11,19
16,REC-506660,10724,excellence noir puissant cacao,lindt,100,autriche,2024-12-09,14
17,REC-323330,14542,fourrs chocolat noir,bjorg,225,france,2024-08-12,22
18,REC-726018,6965,extra dark cocoa,fin carré,100,belgium,2025-05-26,23
19,REC-799477,13302,fibres,wasa,230,belgique,2025-03-19,6

<class 'pandas.DataFrame'>
RangeIndex: 2411 entries, 0 to 2410
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      2411 non-null   str
 1   customer_id   2411 non-null   int64
 2   product_name  2411 non-null   object
 3   brand         2411 non-null   object
 4   raw_weight    2411 non-null   int64
 5   country       2411 non-null   object
 6   order_date    2411 non-null   str
 7   unit_price    2411 non-null   int64
dtypes: int64(3), object(3), str(2)
memory usage: 150.8+ KB

None

(2411, 8)

        customer_id   raw_weight   unit_price
count   2411.000000  2411.000000  2411.000000
mean    9984.200747   179.760265    12.495645
std     2886.557170   143.359481     6.619245
min     5011.000000     1.000000     1.000000
25%     7412.000000   100.000000     7.000000
50%    10103.000000   150.000000    12.000000
75%    12554.500000   250.000000    18.000000
max    14997.000000  1000.000000    24.000000

order_id        0
customer_id     0
product_name    0
brand           0
raw_weight      0
country         0
order_date      0
unit_price      0
dtype: int64

In [140]:
dfc.drop(columns="index",inplace=True)
dfc

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
0,REC-861088,6120,perly,perly,100,morocco,2024-02-22,13
1,REC-900952,12550,prince got chocolat,lu,300,algeria,2024-11-13,1
2,REC-595965,6705,excellence noir prodigieux cacao,lindt excellence,100,argelia,2025-02-02,12
3,REC-942653,8645,tonik,عربي,22,maroc,2024-12-11,14
4,REC-885998,14430,ssame,gerblé,230,belgium,2025-08-21,18
...,...,...,...,...,...,...,...,...
2406,REC-796830,11134,sabls noisette chocolat,bonne maman,150,francia,2024-12-14,21
2407,REC-774268,8212,chocolate for change dark chocolate with orange,coop,100,germany,2025-03-23,14
2408,REC-432494,13398,lait dessert,fin carré,200,france,2025-01-03,17
2409,REC-117507,8050,rusticotti,balocco,700,francia,2025-09-02,21
2410,REC-692469,11809,cheddar onion chutney rolls,higgidy,160,gb,2024-12-07,7

### Saving the file to csv.

In [142]:
dfc.to_csv("cleaned_retailer_dataset.csv")